In [1]:

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import os
import json
import cv2
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.patches as patches

In [2]:
data_path_train = r'C:\Users\Steven\OneDrive - Cal State LA\Documents\train_metadata.json'
with open(data_path_train) as json_file:
    meta_train = json.load(json_file)
    
    
#loading json file for test data
data_path_test = r'C:\Users\Steven\OneDrive - Cal State LA\Documents\test_metadata.json'
with open(data_path_test) as json_file:
    meta_test = json.load(json_file) 

In [3]:
#Finding keys in train dictionary
meta_train.keys()

dict_keys(['annotations', 'images', 'categories', 'genera', 'institutions', 'distances', 'license'])

In [4]:
#creating seperate dataframes from metadata
annotations_train =  pd.json_normalize(meta_train ['annotations'])
categories_train =  pd.json_normalize(meta_train ['categories'])
images_train =  pd.json_normalize(meta_train ['images'])
genera_train =  pd.json_normalize(meta_train ['genera'])
distance_train =  pd.json_normalize(meta_train ['distances'])
licenses_train =  pd.json_normalize(meta_train ['license'])
institutions_train =  pd.json_normalize(meta_train ['institutions'])

In [5]:
del genera_train
del licenses_train
del institutions_train

In [6]:
#Looking at test set
df_test = pd.DataFrame(meta_test)

#creating test data
df_test = df_test.drop(['license'], axis=1)

print(df_test['file_name'])
# adding file path
df_test = df_test[['image_id','file_name']]
df_test['file_path']='C:/Users/Steven/OneDrive - Cal State LA/Documents/image/'+df_test['file_name']


0         000/test-000000.jpg
1         000/test-000001.jpg
2         000/test-000002.jpg
3         000/test-000003.jpg
4         000/test-000004.jpg
                 ...         
210402    223/test-223645.jpg
210403    223/test-223646.jpg
210404    223/test-223647.jpg
210405    223/test-223648.jpg
210406    223/test-223649.jpg
Name: file_name, Length: 210407, dtype: object


In [7]:
# Complete df
df_merge = pd.merge(images_train[['image_id','file_name']],annotations_train[['genus_id','category_id','image_id']] , on='image_id')
df_merge = pd.merge(df_merge[['genus_id','image_id','file_name','category_id']],categories_train[['category_id','scientificName','family','genus','species']] , on='category_id')
df_merge['file_path']='C:/Users/Steven/OneDrive - Cal State LA/Documents/images2/'+df_merge['file_name']
df_merge['name']=df_merge['genus']+' '+df_merge['species']
df_train = df_merge[['category_id','genus_id','image_id','family','genus','species','name','file_name','file_path']]

df_train.head()

category_id  genus_id    image_id    family  genus   species  \
0            0         1  00000__001  Pinaceae  Abies  amabilis   
1            0         1  00000__002  Pinaceae  Abies  amabilis   
2            0         1  00000__003  Pinaceae  Abies  amabilis   
3            0         1  00000__004  Pinaceae  Abies  amabilis   
4            0         1  00000__005  Pinaceae  Abies  amabilis   

             name              file_name  \
0  Abies amabilis  000/00/00000__001.jpg   
1  Abies amabilis  000/00/00000__002.jpg   
2  Abies amabilis  000/00/00000__003.jpg   
3  Abies amabilis  000/00/00000__004.jpg   
4  Abies amabilis  000/00/00000__005.jpg   

                                           file_path  
0  C:/Users/Steven/OneDrive - Cal State LA/Docume...  
1  C:/Users/Steven/OneDrive - Cal State LA/Docume...  
2  C:/Users/Steven/OneDrive - Cal State LA/Docume...  
3  C:/Users/Steven/OneDrive - Cal State LA/Docume...  
4  C:/Users/Steven/OneDrive - Cal State LA/Docume...

In [8]:
df_train['file_name'][2031]

'000/35/00035__042.jpg'

In [9]:
from skimage import util 
from skimage import data, exposure, img_as_float
import matplotlib.pyplot as plt
from skimage import io, exposure, data

In [10]:

import matplotlib.pyplot as plt

from skimage import io, exposure, data

In [12]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from skimage.io import imread, imshow
from skimage.transform import rescale, resize, downscale_local_mean
y=[]
def makeimage(i2,img2):
    #image=mpimg.imread(df_train['file_path'][i2])
    img=imread(df_train['file_path'][i2],as_gray=True)
    img=img[100:665,100:595]
    img=exposure.adjust_sigmoid(img, cutoff=0.5, gain=10, inv=True)
    img2.append(np.reshape(img, (565*495)))
    y.append(df_train['category_id'][i2])
    
    print(len(y))
    #feature_matrix = np.zeros((665,595) )
   #feature_matrix.shape
    
   # for i in range(0,665):
    #    for j in range(0,595):
  #          feature_matrix[i][j] = ((int(image[i,j,0]) + int(image[i,j,1]) + int(image[i,j,2]))/3)
    
    #img2.append(np.reshape(feature_matrix, (665*595))) 
    #features.shape

    #print(features)


i2=0
img2=[]
while i2<500:
    makeimage(i2,img2)
    i2=i2+1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [28]:
from sklearn import preprocessing

img2=np.array(img2)
print(np.array(img2).shape)
X=img2
print(X)
#c
#X=preprocessing.scale(X)

(500, 279675)
0.9913513576624743


In [14]:
y2=np.array(y)
print(y2)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 

In [15]:
import math
import random
seed= 2
np.random.seed(seed)
pp=math.ceil(random.random()*10)

In [16]:
from sklearn.model_selection import train_test_split

In [22]:
from keras.utils import np_utils
X_train=X
y_train = np_utils.to_categorical(y2, max(y2)+1)
print(X_train.shape)
print(y_train.shape)
print(y_train)

(500, 279675)
(500, 8)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [29]:
#4)

def model_creator():

    # define:

    

    # design the structure:

    ## Designing the ANN Structure (with 784 inputs, 10 outputs and 100 neuron in a hidden layer):
    # Declare Sequential model to build our network:
    model = Sequential()
    input_size = 279675
    hidden_neurons = 100
    out_size = max(y2)+1
    # -----------------------------------------
    # first layer: input layer
    # Input layer does not do any processing, so no need to define the input layer in this problem.

    # -----------------------------------------
    # second layer: hidden layer:
    model.add(Dense(hidden_neurons, input_dim = input_size))  # Nuerons
    model.add(Activation('sigmoid')) # Activation

    # -----------------------------------------
    # third layer: output layer:
    model.add(Dense(out_size, input_dim = hidden_neurons))  # Nuerons
    model.add(Activation('softmax')) # Activation

    # compile:

    model.compile(loss='categorical_crossentropy',
              metrics=['accuracy'],
              optimizer='adam')

    # return: 

    return model 

In [30]:
from keras.models import Sequential
from  keras.wrappers.scikit_learn  import  KerasClassifier
from  sklearn.model_selection  import  GridSearchCV
# import the core layers:
from keras.layers import Dense, Dropout, Activation, Flatten


model = KerasClassifier(build_fn = model_creator, verbose=2)

C:\Users\Steven\AppData\Local\Temp/ipykernel_11052/3609852159.py:8: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  model = KerasClassifier(build_fn = model_creator, verbose=2)


In [31]:
batch_size = [30 , 50 , 100 ] 
epochs = [10 , 15 , 20]

param_grid = dict(batch_size=batch_size, epochs=epochs)

grid=GridSearchCV(estimator=model,param_grid=param_grid,scoring='neg_log_loss',cv=10)



In [ ]:
#fitted_model = model.fit(X_train, y_train, batch_size=32, epochs=15, verbose=1)
fitted_model = grid.fit(X_train, y_train)


# batch_size: Integer or None. Number of samples per gradient update. 
# epochs: Number of iterations over the entire x and y training data. 
# verbose: 0, 1, or 2. how to see the training progress. 0 = silent, 1 = progress bar, 2 = one line per epoch.
# validation_split: Float between 0 and 1. Fraction of the training data to be used as validation data. 
# You can add some callbacks to get a view on internal states and statistics of the model during training:
# https://keras.io/callbacks/  

Epoch 1/10
15/15 - 2s - loss: 2.3945 - accuracy: 0.1600 - 2s/epoch - 101ms/step
Epoch 2/10
15/15 - 1s - loss: 2.1564 - accuracy: 0.1933 - 1s/epoch - 86ms/step
Epoch 3/10
15/15 - 1s - loss: 2.0298 - accuracy: 0.2044 - 1s/epoch - 87ms/step
Epoch 4/10
15/15 - 1s - loss: 1.9682 - accuracy: 0.2044 - 1s/epoch - 85ms/step
Epoch 5/10
15/15 - 1s - loss: 1.9541 - accuracy: 0.2022 - 1s/epoch - 86ms/step
Epoch 6/10
15/15 - 1s - loss: 1.9579 - accuracy: 0.2000 - 1s/epoch - 87ms/step
Epoch 7/10
15/15 - 1s - loss: 1.9538 - accuracy: 0.2089 - 1s/epoch - 87ms/step
Epoch 8/10
15/15 - 1s - loss: 1.9573 - accuracy: 0.1933 - 1s/epoch - 87ms/step
Epoch 9/10
15/15 - 1s - loss: 1.9560 - accuracy: 0.2044 - 1s/epoch - 88ms/step
Epoch 10/10
15/15 - 1s - loss: 1.9547 - accuracy: 0.1978 - 1s/epoch - 86ms/step
Epoch 1/10
15/15 - 2s - loss: 2.8095 - accuracy: 0.1422 - 2s/epoch - 150ms/step
Epoch 2/10
15/15 - 1s - loss: 2.3292 - accuracy: 0.1467 - 1s/epoch - 82ms/step
Epoch 3/10
15/15 - 1s - loss: 2.1657 - accuracy: 

In [ ]:
#8)

print("Best: %f using %s" % (fitted_model.best_score_, fitted_model.best_params_))
