In [25]:

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import os
import json
import cv2
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.patches as patches

In [26]:
data_path_train = r'C:\Users\Steven\OneDrive - Cal State LA\Documents\train_metadata.json'
with open(data_path_train) as json_file:
    meta_train = json.load(json_file)
    
    
#loading json file for test data
data_path_test = r'C:\Users\Steven\OneDrive - Cal State LA\Documents\test_metadata.json'
with open(data_path_test) as json_file:
    meta_test = json.load(json_file) 

In [27]:
#Finding keys in train dictionary
meta_train.keys()

dict_keys(['annotations', 'images', 'categories', 'genera', 'institutions', 'distances', 'license'])

In [28]:
#creating seperate dataframes from metadata
annotations_train =  pd.json_normalize(meta_train ['annotations'])
categories_train =  pd.json_normalize(meta_train ['categories'])
images_train =  pd.json_normalize(meta_train ['images'])
genera_train =  pd.json_normalize(meta_train ['genera'])
distance_train =  pd.json_normalize(meta_train ['distances'])
licenses_train =  pd.json_normalize(meta_train ['license'])
institutions_train =  pd.json_normalize(meta_train ['institutions'])

In [29]:

#categories_train['species']=categories_train['species'].astype('category').cat.codes



In [30]:
del genera_train
del licenses_train
del institutions_train

In [31]:
#Looking at test set
df_test = pd.DataFrame(meta_test)

#creating test data
df_test = df_test.drop(['license'], axis=1)

print(df_test['file_name'])
# adding file path
df_test = df_test[['image_id','file_name']]
df_test['file_path']='C:/Users/Steven/OneDrive - Cal State LA/Documents/image/'+df_test['file_name']


0         000/test-000000.jpg
1         000/test-000001.jpg
2         000/test-000002.jpg
3         000/test-000003.jpg
4         000/test-000004.jpg
                 ...         
210402    223/test-223645.jpg
210403    223/test-223646.jpg
210404    223/test-223647.jpg
210405    223/test-223648.jpg
210406    223/test-223649.jpg
Name: file_name, Length: 210407, dtype: object


In [51]:
# Complete df
df_merge = pd.merge(images_train[['image_id','file_name']],annotations_train[['genus_id','category_id','image_id']] , on='image_id')
df_merge = pd.merge(df_merge[['genus_id','image_id','file_name','category_id']],categories_train[['category_id','scientificName','family','genus','species']] , on='category_id')
df_merge['file_path']='C:/Users/Steven/OneDrive - Cal State LA/Documents/images2/'+df_merge['file_name']
df_merge['name']=df_merge['genus']+' '+df_merge['species']
df_train = df_merge[['category_id','genus_id','image_id','family','genus','species','name','file_name','file_path']]

df_train.head()

category_id  genus_id    image_id    family  genus   species  \
0            0         1  00000__001  Pinaceae  Abies  amabilis   
1            0         1  00000__002  Pinaceae  Abies  amabilis   
2            0         1  00000__003  Pinaceae  Abies  amabilis   
3            0         1  00000__004  Pinaceae  Abies  amabilis   
4            0         1  00000__005  Pinaceae  Abies  amabilis   

             name              file_name  \
0  Abies amabilis  000/00/00000__001.jpg   
1  Abies amabilis  000/00/00000__002.jpg   
2  Abies amabilis  000/00/00000__003.jpg   
3  Abies amabilis  000/00/00000__004.jpg   
4  Abies amabilis  000/00/00000__005.jpg   

                                           file_path  
0  C:/Users/Steven/OneDrive - Cal State LA/Docume...  
1  C:/Users/Steven/OneDrive - Cal State LA/Docume...  
2  C:/Users/Steven/OneDrive - Cal State LA/Docume...  
3  C:/Users/Steven/OneDrive - Cal State LA/Docume...  
4  C:/Users/Steven/OneDrive - Cal State LA/Docume...

18

In [114]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from skimage.io import imread, imshow
def makeimage(i2):
    image=mpimg.imread(df_train['file_path'][i2])
    print(df_train['category_id'][i2])
    feature_matrix = np.zeros((1000,626) )
    feature_matrix.shape

    for i in range(0,image.shape[0]):
        for j in range(0,626):
            feature_matrix[i][j] = ((int(image[i,j,0]) + int(image[i,j,1]) + int(image[i,j,2]))/3)

    features = np.reshape(feature_matrix, (image.shape[0]*626)) 
    features.shape

    print(features)
    return features


i2=0
img=[]
while i2<500:
    img.append(makeimage(i2))
    i2=i2+10
img=np.array(img)
print(np.array(img).shape)
#plt.imshow(img[2], cmap=plt.cm.gray)

0
[11.66666667  1.66666667  4.66666667 ...  3.          1.
  1.        ]
0
[4.         2.         2.         ... 2.         1.33333333 2.        ]
0
[0. 0. 0. ... 0. 0. 0.]
0
[52.66666667 57.66666667 55.66666667 ... 49.         47.66666667
 48.66666667]
0
[66.66666667 60.66666667 57.33333333 ... 44.         50.
 45.        ]
0
[105.66666667  94.33333333  78.         ...  45.66666667  43.66666667
  45.66666667]
1
[ 1.66666667  5.66666667 10.66666667 ...  1.          3.
  1.        ]
1
[5.33333333 4.66666667 4.66666667 ... 1.33333333 1.         1.66666667]
1
[4.         2.         6.66666667 ... 1.         2.         3.        ]
1
[44.         42.         35.         ... 28.         42.33333333
 25.33333333]
1
[0. 0. 0. ... 0. 0. 0.]
1
[190.66666667 210.66666667 217.66666667 ...  54.          51.
  51.        ]
1
[33.33333333 37.         47.         ... 30.         28.66666667
 33.66666667]
1
[31.         39.         36.         ... 28.66666667 36.66666667
 34.66666667]
2
[ 0.          3

In [106]:
#y = categories_train['species']

In [107]:
from sklearn import preprocessing
X=preprocessing.scale(img)
X
print(X.shape)
print(X)

(50, 626000)
[[-0.58974859 -0.79160445 -0.69875346 ... -0.78345242 -0.85468758
  -0.84944083]
 [-0.78133359 -0.78441458 -0.75023649 ... -0.80848285 -0.84633776
  -0.82446218]
 [-0.88129097 -0.82755379 -0.78884876 ... -0.85854371 -0.87973705
  -0.87441949]
 ...
 [-0.78966337 -0.77003485 -0.69875346 ... -0.51646118 -0.56244388
  -0.60798049]
 [ 0.65138898  0.53133123  0.45317939 ...  3.12129446  3.10312714
   3.14714415]
 [ 0.55143159  0.55290084  0.2343765  ...  2.06167298  1.97590143
   1.87323269]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [ ]:
#e

from  sklearn.decomposition  import  PCA

k = 50  #  k  is the number of components (new features) after dimensionality reduction

my_pca = PCA(n_components = k)

# X_Train is feature matrix of training set before dimensionality reduction, 

# X_Train_New is feature matrix of training set after dimensionality reduction:

X_train_new = my_pca. fit_transform(X_train)

X_test_new = my_pca. transform(X_test)







In [ ]:
#f

from sklearn import svm


clf=svm.SVC(C=10, kernel='rbf', gamma=0.0005, random_state=1)

#Train the model using the training sets
clf.fit(X_train_new, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test_new)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
confusion_matrix(y_test, y_pred)

In [ ]:
#g)

from sklearn.model_selection import GridSearchCV
 
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000,5e3,1e4,5e4,1e5],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf'],
             }

X_normalized_pca = my_pca.fit_transform(X)

grid = GridSearchCV(svm.SVC(), param_grid,  cv=10)
 
# fitting the model for grid search
grid.fit(X_normalized_pca, y)





print(grid.best_estimator_)